# Generated by Django 5.2.6 on 2025-11-10 12:03

import apps.auths.validators
import django.contrib.auth.password_validation
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Enter the birth date of the user.', null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the city of the user.', max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country of the user.', max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date and time when the user joined.', verbose_name='Date Joined'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='Enter the department of the user.', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Enter the full name of the user.', max_length=200, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter the phone number of the user.', max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', help_text='Select the role of the user.', max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the salary of the user.', max_digits=10, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, help_text='Enter a valid email address.', max_length=100, unique=True, validators=[apps.auths.validators.validate_email_domain], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateField(blank=True, help_text="The date and time of the user's last login.", null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, help_text='Enter a secure password.', max_length=128, null=True, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password'),
        ),
    ]
