# Generated by Django 5.2.6 on 2025-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_customuser_options_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter the first name of the user.', max_length=30, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter the last name of the user.', max_length=30, verbose_name='Last Name'),
        ),
    ]
